id: IAB24C3A8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T06:37:01+00:00'
last_modified: '2022-06-08T16:20:25.092740+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5438
  title: དགེ་རྒན་གྱི་སློབ་གསོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    082B:
      image_group_id: I3CN5440
      title: Volume 1 of dge rgan gyi slob gso/
      total_pages: 140
      order: 1
      base_file: 082B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
