id: P007052
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN5438
  title: དགེ་རྒན་གྱི་སློབ་གསོ།
  author: ''
  volumes:
    a69d25fd815f4513a0883f1f75938677:
      image_group_id: I3CN5440
      title: Volume 1 of dge rgan gyi slob gso/
      volume_number: 1
      total_pages: 140
      base_file: v001.txt
