id: P007052
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5438
  title: དགེ་རྒན་གྱི་སློབ་གསོ།
  author: ''
  volumes:
    a69d25fd815f4513a0883f1f75938677:
      image_group_id: I3CN5440
      title: Volume 1 of dge rgan gyi slob gso/
      volume_number: 1
      total_pages: 140
      base_file: v001.txt
ebook_metadata:
  title: དགེ་རྒན་གྱི་སློབ་གསོ།
  author: ''
  sku: P007052
  cover: cover.jpg
  layers:
  - pagination
