id: P007052
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5438
  title: དགེ་རྒན་གྱི་སློབ་གསོ།
  author: ''
  volumes:
    aa17457742ab4c4c9d259f4955349363:
      image_group_id: I3CN5440
      title: ''
      volume_number: 1
      total_pages: 140
ebook_metadata:
  title: དགེ་རྒན་གྱི་སློབ་གསོ།
  author: ''
  sku: P007052
  cover: cover.jpg
  layers:
  - pagination
